// Summary panel — renders a GroundedSummary. Unverified claims are struck
// through with a tooltip giving the gate reason (spec §7.5).

import type { GroundedSummary } from "../types-summary";

export function Summary({ summary, capabilities }: {
  summary: GroundedSummary | null;
  capabilities: Record<string, { available: boolean; reason: string }>;
}) {
  if (!summary) {
    const llmAvailable = capabilities.llm?.available ?? false;
    return (
      <div className="summary-empty">
        <p>Select a symbol in the editor, or press ⌘⇧K on a function, to see a grounded summary.</p>
        {!llmAvailable && capabilities.llm ? (
          <p className="degraded">LLM: {capabilities.llm.reason}</p>
        ) : null}
      </div>
    );
  }
  const verified = summary.claims.filter((c) => c.entailed).length;
  const total = summary.claims.length;
  const lowConfidence = total > 0 && verified / total < 0.7;
  return (
    <div className="summary">
      <header>
        <strong>{summary.symbol}</strong>
        <span className="dim">
          · verified {verified}/{total}
        </span>
      </header>
      {lowConfidence ? (
        <div className="banner banner-warn">This summary is low-confidence.</div>
      ) : null}
      <pre className="summary-text">
        {summary.claims.map((c, i) => (
          <span key={i} className={c.entailed ? "claim claim-ok" : "claim claim-bad"} title={c.reason ?? ""}>
            {c.text}
            {"\n"}
          </span>
        ))}
      </pre>
      <section className="facts">
        <header>Facts used ({summary.factsGiven.length}):</header>
        <ul>
          {summary.factsGiven.slice(0, 8).map((f) => (
            <li key={f.id}>
              <span className="fact-kind">{f.kind}</span> {f.content}
            </li>
          ))}
          {summary.factsGiven.length > 8 ? (
            <li className="dim">…{summary.factsGiven.length - 8} more</li>
          ) : null}
        </ul>
      </section>
      <footer className="dim">
        Generated by {summary.model} · {summary.generatedAt}
      </footer>
    </div>
  );
}
